cv_k: 3
run_cv_on:
  - resources/configs/mistral.yml
  - resources/configs/llama3.yml
param_grid:
  adapter_config__l1ra_lambda:  # L1-regularisation coefficient
    - 0.1
    - 0.05
    - 0.01
  eta_c:  # Learning rate c vector
    - 1.e-2
    - 1.e-4
  adapter_config__rank_update_ratio:  # Ratio of the training steps after which update ranks
    - 0.01
    - 0.001